name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        compiler: ['gcc-7', 'gcc-8', 'gcc-9', 'clang-6', 'clang-10']
        include:
          - compiler: gcc-7
            packages: gcc-7 g++-7
            env: { 'CC': 'gcc-7', 'CXX': 'g++-7' }
          - compiler: gcc-8
            packages: gcc-8 g++-8
            env: { 'CC': 'gcc-8', 'CXX': 'g++-8' }
          - compiler: gcc-9
            packages: gcc-9 g++-9
            env: { 'CC': 'gcc-9', 'CXX': 'g++-9' }
          - compiler: clang-6
            packages: ''
            env: { 'CC': 'clang-6.0', 'CXX': 'clang++-6.0' }
          - compiler: clang-10
            packages: 'clang-10'
            env: { 'CC': 'clang-10', 'CXX': 'clang++-10' }

    env: ${{ matrix.env }}

    steps:
    - name: Add Clang apt repository
      if: matrix.compiler == 'clang-10'
      run: |
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" \
        | sudo tee -a /etc/apt/sources.list.d/llvm.list
        curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y ${{ matrix.packages }} nasm yasm cmake
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Compile SVT-AV1
      run: |
        ./Build/linux/build.sh static
        ./Bin/Release/SvtAv1EncApp -help
    - name: Compress SVT-AV1 binaries
      if: matrix.compiler == 'gcc-9'
      run: tar czf ./svtav1-current.tar.gz ./Bin/Release/*
    - name: Upload artifact SVT-AV1 (current)
      if: matrix.compiler == 'gcc-9'
      uses: actions/upload-artifact@v1
      with:
        name: svtav1-current
        path: ./svtav1-current.tar.gz

  binary-identical-test:
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-9 g++-9 nasm yasm cmake
    - name: Download videos
      run: |
        wget -nc https://raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master/video.tar.gz || wget -nc http://randomderp.com/video.tar.gz
        tar xf video.tar.gz
        mv -t $HOME akiyo_cif.y4m
        mv -t $HOME Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m
    - name: Checkout SVT-AV1 (master)
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Build SVT-AV1 (master)
      run: |
        mkdir $HOME/master
        mv * $HOME/master
        $HOME/master/Build/linux/build.sh static
    - name: Encode videos (master)
      run: |
        $HOME/master/Bin/Release/SvtAv1EncApp -enc-mode 8 -i $HOME/akiyo_cif.y4m -n 120 -b $HOME/test-master-8bit-m8.ivf
        $HOME/master/Bin/Release/SvtAv1EncApp -enc-mode 0 -i $HOME/akiyo_cif.y4m -n 3 -b $HOME/test-master-8bit-m0.ivf
        $HOME/master/Bin/Release/SvtAv1EncApp -enc-mode 8 -i $HOME/Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m -n 120 -b $HOME/test-master-10bit-m8.ivf
        $HOME/master/Bin/Release/SvtAv1EncApp -enc-mode 0 -i $HOME/Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m -n 3 -b $HOME/test-master-10bit-m0.ivf
    - name: Download artifact SVT-AV1 (current)
      uses: actions/download-artifact@v1
      with:
        name: svtav1-current
    - name: Extract artifact SVT-AV1 (current)
      run: |
        mkdir $HOME/current
        tar xf svtav1-current/svtav1-current.tar.gz -C $HOME/current
    - name: Encode videos (current)
      run: |
        $HOME/current/Bin/Release/SvtAv1EncApp -enc-mode 8 -i $HOME/akiyo_cif.y4m -n 120 -b $HOME/test-pr-8bit-m8.ivf
        $HOME/current/Bin/Release/SvtAv1EncApp -enc-mode 0 -i $HOME/akiyo_cif.y4m -n 3 -b $HOME/test-pr-8bit-m0.ivf
        $HOME/current/Bin/Release/SvtAv1EncApp -enc-mode 8 -i $HOME/Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m -n 120 -b $HOME/test-pr-10bit-m8.ivf
        $HOME/current/Bin/Release/SvtAv1EncApp -enc-mode 0 -i $HOME/Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m -n 3 -b $HOME/test-pr-10bit-m0.ivf
    - name: Binary compare
      run: |
        echo Comparing 8-bit M8: akiyo_cif.y4m
        diff $HOME/test-pr-8bit-m8.ivf $HOME/test-master-8bit-m8.ivf
        echo Comparing 8-bit M0: akiyo_cif.y4m
        diff $HOME/test-pr-8bit-m0.ivf $HOME/test-master-8bit-m0.ivf
        echo Comparing 10-bit M8: Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m
        diff $HOME/test-pr-10bit-m8.ivf $HOME/test-master-10bit-m8.ivf
        echo Comparing 10-bit M0: Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m
        diff $HOME/test-pr-10bit-m0.ivf $HOME/test-master-10bit-m0.ivf
    - name: On fail, compress SVT-AV1 (master)
      if: failure()
      run: tar czf ./svtav1-master.tar.gz $HOME/master/Bin/Release/*
    - name: On fail, upload artifact SVT-AV1 (master)
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: svtav1-master
        path: ./svtav1-master.tar.gz

  # Compile and run tests in shards with only one compiler
  unit-tests:
    runs-on: ubuntu-18.04
    env: { 'CC': 'gcc-9', 'CXX': 'g++-9' }
    strategy:
      matrix:
        index: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
    name: 'Unit Tests (Ubuntu 18.04, GCC 9.x) Shard ${{ matrix.index }}'
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y nasm yasm cmake gcc-9 g++-9
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Compile SVT-AV1 (Release, Tests)
        run: ./Build/linux/build.sh release test
      - name: Run unit tests shard
        run: env GTEST_TOTAL_SHARDS=8 GTEST_SHARD_INDEX=${{ matrix.index }} ./Bin/Release/SvtAv1UnitTests

  e2e-tests:
    runs-on: ubuntu-18.04
    env: { 'CC': 'gcc-9', 'CXX': 'g++-9' }
    strategy:
      matrix:
        index: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
    name: 'E2E Tests (Ubuntu 18.04, GCC 9.x) Shard ${{ matrix.index }}'
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y nasm yasm cmake gcc-9 g++-9
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Compile SVT-AV1 (Release, Tests and TestVectors)
        run: |
          ./Build/linux/build.sh release test
          pushd ./Build/linux/Release
          make TestVectors
          popd
      - name: Run unit tests shard
        run: env SVT_AV1_TEST_VECTOR_PATH="./test/vectors" GTEST_TOTAL_SHARDS=8 GTEST_SHARD_INDEX=${{ matrix.index }} ./Bin/Release/SvtAv1E2ETests --gtest_filter=-*DummySrcTest*
